# version: '3'

services:
  mariadb:
    container_name: mariadb
    # image: mariadb:latest
    build:
      context: mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - inception_net

  wordpress:
    container_name: wordpress
    image: wordpress:php8.2-fpm
    # build:
    #   context: contextPath
    #   dockerfile: Dockerfile
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - ./wp_data:/var/www/html
    networks:
      - inception_net
    restart: always

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8080:80
    # build:
    #   context: contextPath
    #   dockerfile: Dockerfile
    depends_on:
      - wordpress
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/log:/var/log/nginx
      - ./wp_data:/var/www/html
    networks:
      - inception_net
    restart: always

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yoka/data/db
      # device: ${HOME}/data/db
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yoka/data/wp
      # device: ${HOME}/data/wp

networks:
  inception_net:
    name: inception_net
#     driver: bridge